name: PHP Validate
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: echo "BRANCH=$(echo ${GITHUB_HEAD_REF} | tr / -)" >> $GITHUB_ENV >> .env
      - run: echo ${{ env.BRANCH }}
      - uses: elgohr/Publish-Docker-Github-Action@master
        env:
          PHP_VERSION: 7.4
        with:
          name: 22116/request-bundle-ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: PHP_VERSION
          tags: ${{ env.BRANCH }}
      - name: Run tests
        run: docker-compose -f ./tests/E2e/docker-compose.yml run --rm test
