name: PHP Validate
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Test build PHP 7.4
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          PHP_VERSION: 7.4
        with:
          name: 22116/request-bundle-ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: PHP_VERSION
          tags: ${GITHUB_REF##*/}
      - name: E2e tests
        run: docker-compose -f ./tests/E2e/docker-compose.yml run --rm test
