name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Test build PHP 5.6
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: 22116/request-bundle-ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: PHP_VERSION=5.6

      - name: Test build PHP 7.1
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: 22116/request-bundle-ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: PHP_VERSION=7.1

      - name: Test build PHP 7.2
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: 22116/request-bundle-ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: PHP_VERSION=7.2

      - name: Test build PHP 7.3
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: 22116/request-bundle-ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: PHP_VERSION=7.3

      - name: Test build PHP 7.4
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: 22116/request-bundle-ci
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildargs: PHP_VERSION=7.4
